//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social_Media_MDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class direct_messages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public direct_messages()
        {
            this.direct_messages1 = new HashSet<direct_messages>();
            this.notifications = new HashSet<notification>();
        }
    
        public int id_message { get; set; }
        public Nullable<int> creator { get; set; }
        public Nullable<int> id_recipient { get; set; }
        public Nullable<int> parent { get; set; }
        public string content { get; set; }
        public byte read_check { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<direct_messages> direct_messages1 { get; set; }
        public virtual direct_messages direct_messages2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notification> notifications { get; set; }
    }
}
