//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social_Media_MDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class friend
    {
        public int id_user1 { get; set; }
        public int id_user2 { get; set; }
        public Nullable<System.DateTime> add_date { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
