//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social_Media_MDS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class socialappdbEntities : DbContext
    {
        public socialappdbEntities()
            : base("name=socialappdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<action> actions { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<direct_messages> direct_messages { get; set; }
        public virtual DbSet<friend> friends { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<reaction_type> reaction_type { get; set; }
        public virtual DbSet<reaction> reactions { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
